version: '3.7'

services:
    inventory-service:
        image: shubham19/ms-inventory-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - "10000:10000"
        networks: 
            - shopping-service
        depends_on:
            - eureka-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin-server:9411/api/v2/spans
    eureka-server:
        image: shubham19/ms-service-discovery:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - "8761:8761"
        networks: 
            - shopping-service
        environment:
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin-server:9411/api/v2/spans

    order-service:
        image: shubham19/ms-order-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - "8500:8500"
        networks: 
            - shopping-service
        depends_on:
            - eureka-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin-server:9411/api/v2/spans
    product-service:
        image: shubham19/ms-product-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - "8000:8000"
        networks: 
            - shopping-service
        depends_on:
            - eureka-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin-server:9411/api/v2/spans
    api-gateway:
        image: shubham19/ms-api-gateway:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - "8081:8081"
        networks: 
            - shopping-service
        depends_on:
            - eureka-server
            - zipkin-server
        environment:
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
            SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
            MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin-server:9411/api/v2/spans
            
    zipkin-server:
        image: openzipkin/zipkin:2.23
        mem_limit: 300m
        restart: always
        ports:
            - "9411:9411"
        networks:
            - shopping-service

networks:
    shopping-service: