spring:
  application:
    name: api-gateway-service
  cloud:
   discovery:
    enabled: true
   gateway:
       routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
          - Path=/api/product/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
          - Path=/api/order/**
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
          - Path=/api/inventory/**
      
    
logging:
  level:
    root: DEBUG
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinationLocator: DEBUG

#Product Service Routes
server:
  port: 8081
        